//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagement.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [KnownType(typeof(Address))]
    public partial class Address
    {

        public int AddID { get; set; }

        public string AddStreet { get; set; }

        public Nullable<int> AddZip { get; set; }

        public string AddCity { get; set; }

        public string AddState { get; set; }

        public int EmpID { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Employee Employee { get; set; }
    }
}
