//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [KnownType(typeof(Employee))]
    public partial class Employee
    {
        public Employee()
        {
            this.Addresses = new HashSet<Address>();
        }


        public int EmpID { get; set; }

        public string EmpFirstName { get; set; }

        public string EmpLastName { get; set; }

        public Nullable<int> EmpAge { get; set; }

        public virtual ICollection<Address> Addresses { get; set; }
    }
}
